In [1]:
import pandas as pd
df = pd.read_csv("IRIS.csv")

In [2]:
df

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

# Groupby function & different aggregations

## Min, max

In [3]:
df.groupby("species").aggregate("max")

                 sepal_length  sepal_width  petal_length  petal_width
species
Iris-setosa               5.8          4.4           1.9          0.6
Iris-versicolor           7.0          3.4           5.1          1.8
Iris-virginica            7.9          3.8           6.9          2.5

In [4]:
df.groupby("species").aggregate("min")

                 sepal_length  sepal_width  petal_length  petal_width
species
Iris-setosa               4.3          2.3           1.0          0.1
Iris-versicolor           4.9          2.0           3.0          1.0
Iris-virginica            4.9          2.2           4.5          1.4

## Avg/mean

In [5]:
df.groupby("species").aggregate("mean")

                 sepal_length  sepal_width  petal_length  petal_width
species
Iris-setosa             5.006        3.418         1.464        0.244
Iris-versicolor         5.936        2.770         4.260        1.326
Iris-virginica          6.588        2.974         5.552        2.026

## Count

In [6]:
df.groupby("species").aggregate("count")

                 sepal_length  sepal_width  petal_length  petal_width
species
Iris-setosa                50           50            50           50
Iris-versicolor            50           50            50           50
Iris-virginica             50           50            50           50

## Sum

In [7]:
df.groupby("species").aggregate("sum")

                 sepal_length  sepal_width  petal_length  petal_width
species
Iris-setosa             250.3        170.9          73.2         12.2
Iris-versicolor         296.8        138.5         213.0         66.3
Iris-virginica          329.4        148.7         277.6        101.3

# Specifying aggregations per column

In [8]:
df.groupby("species").aggregate({"sepal_length": "mean"})

                 sepal_length
species
Iris-setosa             5.006
Iris-versicolor         5.936
Iris-virginica          6.588

In [9]:
df.groupby("species").aggregate({"sepal_length": "mean", "sepal_length": "max"})

                 sepal_length
species
Iris-setosa               5.8
Iris-versicolor           7.0
Iris-virginica            7.9

In [10]:
df.groupby("species").aggregate({"sepal_length": "mean", "petal_length": "max"})

                 sepal_length  petal_length
species
Iris-setosa             5.006           1.9
Iris-versicolor         5.936           5.1
Iris-virginica          6.588           6.9

In [ ]:
df["petal_length"] = df["petal_length"] / 2

df.petal_length.map(lambda r: r/2)

df.petal_length.apply(lambda r: r/2)

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

# Sorting

In [3]:
df.sort_values(by="sepal_length", ascending=False)

     sepal_length  sepal_width  petal_length  petal_width         species
131           7.9          3.8           6.4          2.0  Iris-virginica
122           7.7          2.8           6.7          2.0  Iris-virginica
118           7.7          2.6           6.9          2.3  Iris-virginica
117           7.7          3.8           6.7          2.2  Iris-virginica
135           7.7          3.0           6.1          2.3  Iris-virginica
..            ...          ...           ...          ...             ...
41            4.5          2.3           1.3          0.3     Iris-setosa
42            4.4          3.2           1.3          0.2     Iris-setosa
8             4.4          2.9           1.4          0.2     Iris-setosa
38            4.4          3.0           1.3          0.2     Iris-setosa
13            4.3          3.0           1.1          0.1     Iris-setosa

[150 rows x 5 columns]

In [4]:
df.sort_values(by="sepal_length", ascending=True)

     sepal_length  sepal_width  petal_length  petal_width         species
13            4.3          3.0           1.1          0.1     Iris-setosa
8             4.4          2.9           1.4          0.2     Iris-setosa
42            4.4          3.2           1.3          0.2     Iris-setosa
38            4.4          3.0           1.3          0.2     Iris-setosa
41            4.5          2.3           1.3          0.3     Iris-setosa
..            ...          ...           ...          ...             ...
122           7.7          2.8           6.7          2.0  Iris-virginica
117           7.7          3.8           6.7          2.2  Iris-virginica
118           7.7          2.6           6.9          2.3  Iris-virginica
135           7.7          3.0           6.1          2.3  Iris-virginica
131           7.9          3.8           6.4          2.0  Iris-virginica

[150 rows x 5 columns]

In [5]:
df.sort_index()

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [6]:
df.sort_values(by=["sepal_length", "sepal_width"], ascending=False)

     sepal_length  sepal_width  petal_length  petal_width         species
131           7.9          3.8           6.4          2.0  Iris-virginica
117           7.7          3.8           6.7          2.2  Iris-virginica
135           7.7          3.0           6.1          2.3  Iris-virginica
122           7.7          2.8           6.7          2.0  Iris-virginica
118           7.7          2.6           6.9          2.3  Iris-virginica
..            ...          ...           ...          ...             ...
41            4.5          2.3           1.3          0.3     Iris-setosa
42            4.4          3.2           1.3          0.2     Iris-setosa
38            4.4          3.0           1.3          0.2     Iris-setosa
8             4.4          2.9           1.4          0.2     Iris-setosa
13            4.3          3.0           1.1          0.1     Iris-setosa

[150 rows x 5 columns]

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [ ]:
df.sepal_length.astype("string")

In [10]:
df.isna().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64