# Pandas Practice: Iris Dataset

In this notebook, you'll practice common Pandas operations using the Iris dataset.

Assumption:
- `IRIS.csv` exists in the same directory as this notebook.

Fill in the blanks (`_____`) in each code cell.

In [55]:
import pandas as pd


# Load the dataset into a DataFrame named df
df = pd.read_csv("IRIS.csv")

# Display the first 5 rows
df.head(5)

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

## Exercise 1: Dataset Shape

Find:
- Number of rows
- Number of columns

In [56]:
rows, cols = df.shape

print("Rows:", rows)
print("Columns:", cols)

Rows: 150
Columns: 5

## Exercise 2: Column Names

Display all column names in the dataset.

In [57]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='str')

## Exercise 3: Dataset Information

Display summary information about the DataFrame.

In [58]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

## Exercise 4: Basic Statistics

Generate descriptive statistics for all numeric columns.

In [59]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

## Exercise 5: Select One Column

Display only the sepal length column.

Hint: Use bracket notation.

In [60]:
df["sepal_length"]

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length, Length: 150, dtype: float64

## Exercise 6: Select Multiple Columns

Display:
- sepal_length
- petal_length

In [61]:
df[[ "sepal_length", "petal_length" ]]

     sepal_length  petal_length
0             5.1           1.4
1             4.9           1.4
2             4.7           1.3
3             4.6           1.5
4             5.0           1.4
..            ...           ...
145           6.7           5.2
146           6.3           5.0
147           6.5           5.2
148           6.2           5.4
149           5.9           5.1

[150 rows x 2 columns]

## Exercise 7: Filter Rows

Display only flowers whose species is Iris-setosa.

In [62]:
setosa_df = df[df["species"] == "Iris-setosa"]

setosa_df.head(20)

    sepal_length  sepal_width  petal_length  petal_width      species
0            5.1          3.5           1.4          0.2  Iris-setosa
1            4.9          3.0           1.4          0.2  Iris-setosa
2            4.7          3.2           1.3          0.2  Iris-setosa
3            4.6          3.1           1.5          0.2  Iris-setosa
4            5.0          3.6           1.4          0.2  Iris-setosa
5            5.4          3.9           1.7          0.4  Iris-setosa
6            4.6          3.4           1.4          0.3  Iris-setosa
7            5.0          3.4           1.5          0.2  Iris-setosa
8            4.4          2.9           1.4          0.2  Iris-setosa
9            4.9          3.1           1.5          0.1  Iris-setosa
10           5.4          3.7           1.5          0.2  Iris-setosa
11           4.8          3.4           1.6          0.2  Iris-setosa
12           4.8          3.0           1.4          0.1  Iris-setosa
13           4.3          3.0           1.1          0.1  Iris-setosa
14           5.8          4.0           1.2          0.2  Iris-setosa
15           5.7          4.4           1.5          0.4  Iris-setosa
16           5.4          3.9           1.3          0.4  Iris-setosa
17           5.1          3.5           1.4          0.3  Iris-setosa
18           5.7          3.8           1.7          0.3  Iris-setosa
19           5.1          3.8           1.5          0.3  Iris-setosa

## Exercise 8: Count Species

Count how many flowers belong to each species.

In [63]:
df["species"].value_counts()

species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

## Exercise 9: Calculate Mean

Find the average sepal length.

In [64]:
total_sum = df['sepal_length'].sum()
row = len(df)
mean = total_sum / row
print(mean)

5.843333333333334

## Exercise 10: Find Maximum Value

Find the largest petal length.

In [65]:
df["petal_length"].max

<bound method Series.max of 0      1.4
1      1.4
2      1.3
3      1.5
4      1.4
      ...
145    5.2
146    5.0
147    5.2
148    5.4
149    5.1
Name: petal_length, Length: 150, dtype: float64>

## Exercise 11: Sort Data

Sort the dataset by sepal length in ascending order.

In [66]:
df.sort_values("sepal_length")

     sepal_length  sepal_width  petal_length  petal_width         species
13            4.3          3.0           1.1          0.1     Iris-setosa
8             4.4          2.9           1.4          0.2     Iris-setosa
42            4.4          3.2           1.3          0.2     Iris-setosa
38            4.4          3.0           1.3          0.2     Iris-setosa
41            4.5          2.3           1.3          0.3     Iris-setosa
..            ...          ...           ...          ...             ...
122           7.7          2.8           6.7          2.0  Iris-virginica
117           7.7          3.8           6.7          2.2  Iris-virginica
118           7.7          2.6           6.9          2.3  Iris-virginica
135           7.7          3.0           6.1          2.3  Iris-virginica
131           7.9          3.8           6.4          2.0  Iris-virginica

[150 rows x 5 columns]

## Exercise 12: Sort Descending

Sort by petal width from largest to smallest.

In [67]:
df.sort_values(
    by="petal_width",
    ascending=False
)

     sepal_length  sepal_width  petal_length  petal_width         species
144           6.7          3.3           5.7          2.5  Iris-virginica
109           7.2          3.6           6.1          2.5  Iris-virginica
100           6.3          3.3           6.0          2.5  Iris-virginica
114           5.8          2.8           5.1          2.4  Iris-virginica
136           6.3          3.4           5.6          2.4  Iris-virginica
..            ...          ...           ...          ...             ...
9             4.9          3.1           1.5          0.1     Iris-setosa
12            4.8          3.0           1.4          0.1     Iris-setosa
32            5.2          4.1           1.5          0.1     Iris-setosa
34            4.9          3.1           1.5          0.1     Iris-setosa
37            4.9          3.1           1.5          0.1     Iris-setosa

[150 rows x 5 columns]

## Exercise 13: Group By Species

Calculate the average sepal length for each species.

In [68]:
df.groupby("species")["sepal_length"].mean()

species
Iris-setosa        5.006
Iris-versicolor    5.936
Iris-virginica     6.588
Name: sepal_length, dtype: float64

## Exercise 14: Multiple Aggregations

For each species, calculate:
- Mean sepal length
- Maximum sepal length

In [69]:
df.groupby("species")["sepal_length"].agg(
    ["mean", "max"]
)

                  mean  max
species
Iris-setosa      5.006  5.8
Iris-versicolor  5.936  7.0
Iris-virginica   6.588  7.9

## Exercise 15: Create a New Column

Create a new column called `petal_area`.

Formula:

petal_length × petal_width

In [70]:
df["petal_area"] = (
    df["petal_length"]
    *
    df["petal_width"]
)

df.head()

,sepal_length,sepal_width,petal_length,petal_width,species,petal_area
0,5.1,3.5,1.4,0.2,Iris-setosa,0.28
1,4.9,3.0,1.4,0.2,Iris-setosa,0.28
2,4.7,3.2,1.3,0.2,Iris-setosa,0.26
3,4.6,3.1,1.5,0.2,Iris-setosa,0.30
4,5.0,3.6,1.4,0.2,Iris-setosa,0.28

## Exercise 16: Filter Using Multiple Conditions

Find flowers where:
- petal_length > 5
- petal_width > 1.5

In [71]:
df[
    (df["petal_length"] > 5)
    &
    (df["petal_width"] > 1.5)
]

,sepal_length,sepal_width,petal_length,petal_width,species,petal_area
83,6.0,2.7,5.1,1.6,Iris-versicolor,8.16
100,6.3,3.3,6.0,2.5,Iris-virginica,15.00
101,5.8,2.7,5.1,1.9,Iris-virginica,9.69
102,7.1,3.0,5.9,2.1,Iris-virginica,12.39
103,6.3,2.9,5.6,1.8,Iris-virginica,10.08
104,6.5,3.0,5.8,2.2,Iris-virginica,12.76
105,7.6,3.0,6.6,2.1,Iris-virginica,13.86
107,7.3,2.9,6.3,1.8,Iris-virginica,11.34
108,6.7,2.5,5.8,1.8,Iris-virginica,10.44
109,7.2,3.6,6.1,2.5,Iris-virginica,15.25
110,6.5,3.2,5.1,2.0,Iris-virginica,10.20
111,6.4,2.7,5.3,1.9,Iris-virginica,10.07
112,6.8,3.0,5.5,2.1,Iris-virginica,11.55
114,5.8,2.8,5.1,2.4,Iris-virginica,12.24
115,6.4,3.2,5.3,2.3,Iris-virginica,12.19
116,6.5,3.0,5.5,1.8,Iris-virginica,9.90
117,7.7,3.8,6.7,2.2,Iris-virginica,14.74
118,7.7,2.6,6.9,2.3,Iris-virginica,15.87
120,6.9,3.2,5.7,2.3,Iris-virginica,13.11
122,7.7,2.8,6.7,2.0,Iris-virginica,13.40
124,6.7,3.3,5.7,2.1,Iris-virginica,11.97
125,7.2,3.2,6.0,1.8,Iris-virginica,10.80
128,6.4,2.8,5.6,2.1,Iris-virginica,11.76
129,7.2,3.0,5.8,1.6,Iris-virginica,9.28
130,7.4,2.8,6.1,1.9,Iris-virginica,11.59
131,7.9,3.8,6.4,2.0,Iris-virginica,12.80
132,6.4,2.8,5.6,2.2,Iris-virginica,12.32
135,7.7,3.0,6.1,2.3,Iris-virginica,14.03
136,6.3,3.4,5.6,2.4,Iris-virginica,13.44
137,6.4,3.1,5.5,1.8,Iris-virginica,9.90
139,6.9,3.1,5.4,2.1,Iris-virginica,11.34
140,6.7,3.1,5.6,2.4,Iris-virginica,13.44
141,6.9,3.1,5.1,2.3,Iris-virginica,11.73
142,5.8,2.7,5.1,1.9,Iris-virginica,9.69
143,6.8,3.2,5.9,2.3,Iris-virginica,13.57
144,6.7,3.3,5.7,2.5,Iris-virginica,14.25
145,6.7,3.0,5.2,2.3,Iris-virginica,11.96
147,6.5,3.0,5.2,2.0,Iris-virginica,10.40
148,6.2,3.4,5.4,2.3,Iris-virginica,12.42
149,5.9,3.0,5.1,1.8,Iris-virginica,9.18

## Exercise 17: Unique Species

Display all unique species names.

In [72]:
df["species"].unique()

<StringArray>
['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']
Length: 3, dtype: str

## Exercise 18: Missing Values

Count missing values in each column.

In [73]:
df._____().sum()

AttributeError: 'DataFrame' object has no attribute '_____'

## Exercise 19: Row Selection with loc

Display rows 0 through 4 and all columns.

In [ ]:
df._____[0:4, :]

## Exercise 20: Species Summary Challenge

Compute the average of:
- sepal_length
- sepal_width
- petal_length
- petal_width

for each species.

In [ ]:
df.groupby("species")[
    [
        "sepal_length",
        "sepal_width",
        "petal_length",
        "petal_width",
    ]
]._____

# Bonus Challenge

Create a DataFrame containing only the top 10 flowers with the largest petal area.

In [ ]:
top10 = (
    df.sort_values(
        by="_____",
        ascending=_____
    )
    .head(_____)
)

top10

# Bonus Challenge 2: Species Comparison Report

Create a summary table where each species has:

- Average sepal length
- Average sepal width
- Average petal length
- Average petal width

Then sort the resulting table by average petal length in descending order.

In [ ]:
species_report = (
    df
    .groupby("_____")
    .agg({
        "sepal_length": "_____",
        "sepal_width": "_____",
        "petal_length": "_____",
        "petal_width": "_____",
    })
    .sort_values(
        by="_____",
        ascending=_____
    )
)

species_report

# Bonus Challenge 3: Most Typical Flower

Find all flowers whose sepal length is greater than the overall average sepal length.

Display:
- sepal_length
- sepal_width
- species

In [ ]:
avg_sepal_length = df["sepal_length"]._____

result = df[
    df["sepal_length"] > _____
][
    [
        "sepal_length",
        "sepal_width",
        "species"
    ]
]

result.head()

# Bonus Challenge 4: Species with Largest Average Petal Area

1. Create a new column called `petal_area`.
2. Compute the average petal area for each species.
3. Display the species with the largest average petal area.

In [ ]:
df["petal_area"] = (
    df["petal_length"]
    *
    df["_____"]
)

avg_area = (
    df.groupby("_____")["petal_area"]
    ._____
    ()
)

avg_area.sort_values(
    ascending=_____
).head(_____)

# Bonus Challenge 5: Build Your Own Pivot Table

Create a pivot table that shows the mean petal length for each species.

In [ ]:
pd._____(
    df,
    values="_____",
    index="_____",
    aggfunc="_____"
)